issues:
  max-same-issues: 0
  max-issues-per-linter: 0
  exclude-dirs:
   - wordlists
  exclude-rules:
    - path: bip39_test\.go
      text: "Function 'testVectors' is too long"
      linters:
        - funlen
    - path: (cmd/cli/bip39|bip39_test|example_test)\.go
      linters:
        - lll
    - path: bip39\.go
      text: "ST1005: error strings should not be capitalized"
      linters:
        - stylecheck
    - path: (cmd/cli/bop39|bip39|bip39_test|example_test)\.go
      text: "is not allowed from list 'Main'"
      linters:
        - depguard
    - path: cmd/cli/bip39\.go
      text: "lines are duplicate of"
      linters:
        - dupl
    - path: cmd/cli/bip39\.go
      text: "Function 'main' is too long"
      linters:
        - funlen
    - path: cmd/cli/bip39\.go
      text: "make it a constant"
      linters:
        - goconst
    - path: cmd/cli/bip39\.go
      text: "parameter 'cCtx' seems to be unused"
      linters:
        - revive    

linters-settings:
  dupl:
    threshold: 20
  errcheck:
    check-type-assertions: false
    check-blank: false
  goconst:
    min-occurrences: 2
  gocyclo:
    min-complexity: 7
  misspell:
    locale: US
  nakedret:
    max-func-lines: 0
  unparam:
    check-exported: false
  govet:
    enable:
      - fieldalignment

linters:
  enable:
    - asciicheck
    - depguard
    - dogsled
    - dupl
    - errcheck
    - funlen
    - goconst
    - gocognit
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - goimports
    - revive
    - gosimple
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nestif
    - prealloc
    - copyloopvar
    - staticcheck
    - stylecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl
